project:
  type: book
  execute-dir: project

book:
  title: "데이터마이닝 기법과 응용: R 예제"
  author: "전치혁, 이혜선, 이종석, 이영록"
  date: today
  chapters:
    - index.qmd
    - part: "예측"
      chapters:
        - chapters/ch02_regression.qmd
        - chapters/ch03_regularized_regression.qmd
    - part: "분류분석"
      chapters: 
        - chapters/ch05_classification.qmd
        - chapters/ch06_logistic_regression.qmd
        - chapters/ch07_da.qmd
        - chapters/ch09_svm.qmd
    - part: "군집분석"
      chapters:
        - chapters/ch11_cluster.qmd
        - chapters/ch12_cluster.qmd
        - chapters/ch13_cluster_dbscan.qmd
    - part: "연관규칙"
      chapters: 
        - chapters/ch15_association_rule.qmd
        - chapters/ch16_recommender_system.qmd
  repo-url: https://github.com/youngroklee-ml/data-mining-techniques

number-sections: false

format:
  html:
    theme: cosmo