project:
  type: book
  execute-dir: project

book:
  title: "데이터마이닝 기법과 응용: R 예제"
  author: "전치혁, 이혜선, 이종석, 이영록"
  date: today
  chapters:
    - index.qmd
    - chapters/ch11_cluster.qmd
    - chapters/ch12_cluster.qmd
    - chapters/ch13_cluster_dbscan.qmd
  repo-url: https://github.com/youngroklee-ml/data-mining-techniques

number-sections: false

format:
  html:
    theme: cosmo