# 12장 계층적 군집방법


## (예 12.1)

데이터 읽기

```{r}
dat1 <- read.csv("data/ch12_dat1.csv")

dat2 <- dat1[, -1]
```


유클리디안 거리

```{r}
D1 <- dist(dat2)
D1 <- round(D1, 2)
D1
```


평균연결법

```{r}
hc_c <- hclust(D1, method = "average")
plot(hc_c,
  hang = -1, cex = 0.7, main = "Average linkage with Euclidean distance",
  ylab = "Distance", xlab = "observation"
)
```


## (예 12.2)

데이터 읽기

```{r}
dat1 <- read.csv("data/ch12_dat2.csv")

dat2 <- dat1[, -1]
```

유클리디안 거리

```{r}
D1 <- dist(dat2)
D1 <- round(D1, 2)
D1
```

워드 방법

```{r}
hc_c <- hclust(D1, method = "ward.D2")
plot(hc_c,
  hang = -1, cex = 1, main = "Ward's linkage with Euclidean distance",
  ylab = "Distance", xlab = "observation"
)
```


## (예 12.3)

패키지 로드

```{r}
library(cluster)
```


데이터 읽기

```{r}
dat1 <- read.csv("data/ch12_dat3.csv")

dat2 <- dat1[, -1]
```


다이아나 방법

```{r}
clus_diana <- diana(dat2)

plot(clus_diana, which.plot = 2, main = "Dendrogram of Diana")
```


## (예 12.4)

데이터 로드

```{r}
dat1 <- read.csv("data/ch12_dat2.csv")

dat2 <- dat1[, -1]
```

패키지 로드

```{r}
library(factoextra)
```

군집수 결정 - total within sum of square

```{r}
fviz_nbclust(dat2, kmeans, method = "wss", k.max = 5)
```

군집수 결정 - gap statistics

```{r}
fviz_nbclust(dat2, kmeans, method = "gap_stat", k.max = 5)
```

군집수 결정 - average silhouette width

```{r}
fviz_nbclust(dat2, kmeans, method = "silhouette", k.max = 5)
```


